--
-- Data for Name: uea_curso; Type: TABLE DATA; Schema: public; Owner: ueasistemas
--
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 1, 2, ' ', 'Ciências Biológicas', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 2, 2, ' ', 'História', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 3, 2, ' ', 'Pedagogia', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 4, 2, ' ', 'Ciências Da Religião', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 5, 2, ' ', 'Letras', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 6, 2, ' ', 'Pedagogia (licenciatura Intercultural Indígena)', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 7, 2, ' ', 'Geografia', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 8, 2, ' ', 'Matemática', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 9, 5, ' ', 'Dança', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 10, 5, ' ', 'Música-regência', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 11, 5, ' ', 'Música-canto', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 12, 5, ' ', 'Teatro', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 13, 5, ' ', 'Música-instrumento', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 14, 5, ' ', 'Turismo', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 15, 3, ' ', 'Enfermagem', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 16, 3, ' ', 'Odontologia', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 17, 3, ' ', 'Farmacia', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 18, 3, ' ', 'Saúde Coletiva', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 19, 3, ' ', 'Medicina', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 20, 4, ' ', 'Administração', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 21, 4, ' ', 'Ciências Econômicas', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 22, 4, ' ', 'Segurança Pública E Do Cidadão', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 23, 4, ' ', 'Arqueologia', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 24, 4, ' ', 'Ciências Militar E Segurança Pública', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 25, 4, ' ', 'Ciências Contábeis', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 26, 4, ' ', 'Direito', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 27, 1, ' ', 'Engenharia Básico', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 28, 1, ' ', 'Engenharia Controle E Automação', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 29, 1, ' ', 'Engenharia Eletrônica', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 30, 1, ' ', 'Engenharia Mecânica', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 31, 1, ' ', 'Meteorologia', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 32, 1, ' ', 'Licenciatura Em Computação', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 33, 1, ' ', 'Tecnologia Em Jogos Digitais', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 34, 1, ' ', 'Tecnologia Em Eletrônica', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 35, 1, ' ', 'Engenharia Civil', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 36, 1, ' ', 'Engenharia De Materiais', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 37, 1, ' ', 'Engenharia Eletrica', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 38, 1, ' ', 'Engenharia Naval', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 39, 1, ' ', 'Sistema De Informação', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 40, 1, ' ', 'Licenciatura Em Informação', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 41, 1, ' ', 'Tecnologia Em Analise Desenvolvimento Sistemas', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 42, 1, ' ', 'Tecnologia Em Manutenção Mecânica', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 43, 1, ' ', 'Engenharia Computação', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 44, 1, ' ', 'Engenharia De Produção', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 45, 1, ' ', 'Engenharia Mecatrônica', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 46, 1, ' ', 'Engenharia Química', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 47, 1, ' ', 'Licenciatura Em Física', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 48, 1, ' ', 'Licenciatura Em Química', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 49, 1, ' ', 'Tecnologia Em Automação Industrial', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 50, 1, ' ', 'Tecnologia Em Processamento De Dados', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 51, 9, ' ', 'Ciências Econômicas', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 52, 9, ' ', 'Licenciatura Em Ciências Biológicas', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 53, 9, ' ', 'Licenciatura Em Informática', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 54, 9, ' ', 'Licenciatura Em Pedagogia (licenciatura Intercultural Indígena)', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 55, 9, ' ', 'Tecnologia Em Gestão Comercial', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 56, 9, ' ', 'Tecnologia Em Prod Pesqueira', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 57, 9, ' ', 'Direito', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 58, 9, ' ', 'Educação Física', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 59, 9, ' ', 'Licenciatura Em Matemática', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 60, 9, ' ', 'Tecnologia Em Agroecologia', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 61, 9, ' ', 'Tecnologia Em Logistica', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 62, 9, ' ', 'Tecnologia Em Construção Naval', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 63, 9, ' ', 'Engenharia Florestal', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 64, 9, ' ', 'Licenciatura Em Letras (língua Portuguesa)', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 65, 9, ' ', 'Licenciatura Em Pedagogia', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 66, 9, ' ', 'Tecnologia Em Alimentos', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 67, 9, ' ', 'Tecnologia Em Petróleo E Gás', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 68, 65, ' ', 'Ciências Econômicas', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 69, 65, ' ', 'Licenciatura Em Geografia', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 70, 65, ' ', 'Licenciatura Pedagogia (licenciatura Intercultural Indígena)', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 71, 65, ' ', 'Tecnologia Em Gestão Comercial', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 72, 65, ' ', 'Tecnologia Em Prod Pesqueira', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 73, 65, ' ', 'Saúde Coletiva', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 74, 65, ' ', 'Licenciatura Em Letras (lingua Portuguesa)', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 75, 65, ' ', 'Tecnologia Em Agroecologia', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 76, 65, ' ', 'Tecnologia Em Gestão Pública', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 77, 65, ' ', 'Licenciatura Em Ciência Biológicas', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 78, 65, ' ', 'Licenciatura Pedagogia', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 79, 65, ' ', 'Tecnologia Em Gestão Ambiental', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 80, 65, ' ', 'Tecnologia Em Logistica', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 81, 6, ' ', 'Ciências Econômicas', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 82, 6, ' ', 'Licenciatura Em Ciências Biológicas', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 83, 6, ' ', 'Licenciatura Em História', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 84, 6, ' ', 'Licenciatura Pedagogia (licenciatura Intercultural Indígena)', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 85, 6, ' ', 'Tecnologia Em Logistica', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 86, 6, ' ', 'Direito', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 87, 6, ' ', 'Licenciatura Em Física', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 88, 6, ' ', 'Licenciatura Em Letras (língua Portuguesa)', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 89, 6, ' ', 'Licenciatura Em Química', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 90, 6, ' ', 'Tecnologia Em Gestão De Turismo', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 91, 6, ' ', 'Enfermagem', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 92, 6, ' ', 'Licenciatura Em Geografia', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 93, 6, ' ', 'Licenciatura Em Pedagogia', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 94, 6, ' ', 'Tecnologia Em Gestão Comercial', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 95, 6, ' ', 'Tecnologia Em Alimentos', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 96, 11, ' ', 'Saúde Coletiva', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 97, 11, ' ', 'Licenciatura Em Letras (língua Portuguesa)', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 98, 11, ' ', 'Licenciatura Em Pedagogia (licenciatura Intercultural Indig', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 99, 11, ' ', 'Tecnologia Em Logística', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 100, 11, ' ', 'Licenciatura Em Ciências Biológicas', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 101, 11, ' ', 'Licenciatura Em Matemática', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 102, 11, ' ', 'Licenciatura Em Química', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 103, 11, ' ', 'Tecnologia Em Gestão De Turismo', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 104, 11, ' ', 'Licenciatura Em Educação Física', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 105, 11, ' ', 'Licenciatura Em Pedagogia', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 106, 11, ' ', 'Tecnologia Em Gestão Comercial', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 107, 8, ' ', 'Ciências Econômicas', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 108, 8, ' ', 'Licenciatura Em Educação Física', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 109, 8, ' ', 'Licenciatura Em Matemática', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 110, 8, ' ', 'Gestão Comercial', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 111, 8, ' ', 'Direito', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 112, 8, ' ', 'Licenciatura Em Geografia', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 113, 8, ' ', 'Licenciatura Em Pedagogia', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 114, 8, ' ', 'Tecnologia Em Logística', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 115, 8, ' ', 'Licenciatura Em Ciências Biológicas', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 116, 8, ' ', 'Licenciatura Em Letras (língua Portuguesa)', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 117, 8, ' ', 'Licenciatura Em  Pedagogia (licenciatura Intercultural Indígena)', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 118, 8, ' ', 'Tecnologia Em Gestão De Turismo', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 119, 7, ' ', 'Ciências Econômicas', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 120, 7, ' ', 'Direito', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 121, 7, ' ', 'Licenciatura Em  Física        	', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 122, 7, ' ', 'Licenciatura Em  Geografia', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 123, 7, ' ', 'Licenciatura Em  Letras (língua Inglesa 2ª Licenciatura)   	', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 124, 7, ' ', 'Licenciatura Em  Letras (língua Portuguesa)', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 125, 7, ' ', 'Licenciatura Em  Pedagogia', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 126, 7, ' ', 'Licenciatura Em  Pedagogia (licenciatura Intercultural Indígena)', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 127, 7, ' ', 'Licenciatura Em  Ciências Biológicas', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 128, 7, ' ', 'Licenciatura Em  História', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 129, 7, ' ', 'Licenciatura Em  Matemática', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 130, 20, ' ', 'Núcleos De Ensino Superior', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 131, 14, ' ', 'Núcleos De Ensino Superior', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 132, 12, ' ', 'Núcleos De Ensino Superior', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 133, 12, ' ', 'Nova Olinda Do Norte - 23', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 134, 12, ' ', 'Núcleos De Ensino Superior', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 135, 17, ' ', 'Núcleos De Ensino Superior', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 136, 21, ' ', 'Núcleos De Ensino Superior', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 137, 18, ' ', 'Núcleos De Ensino Superior', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 138, 16, ' ', 'Núcleos De Ensino Superior', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 139, 22, ' ', 'Núcleos De Ensino Superior', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 140, 19, ' ', 'Núcleos De Ensino Superior', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 141, 15, ' ', 'Núcleos De Ensino Superior', 1);
INSERT INTO public.uea_curso (curso_id, curso_unidade_id, curso_sigla, curso_nome, curso_status) VALUES ( 142, 13, ' ', 'Núcleos De Ensino Superior', 1);
