
--
-- Data for Name: uea_unidade; Type: TABLE DATA; Schema: public; Owner: ueasistemas
--

INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (1, 'Escola Superior de Tecnologia', 'EST', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (2, 'Escola Normal Superior', 'ENS', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (3, 'Escola Superior de Ciencias Saude', 'ESA', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (4, 'Escola Superior de Ciencias Sociais', 'ESO', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (5, 'Escola Superior de Artes e Turismo', 'ESAT', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (6, 'Centro de Estudos Superiores de Parintins', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (7, 'Centro de Estudos Superiores de Tefé', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (8, 'Centro de Estudos Superiores de Tabatinga', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (9, 'Centro de Estudos Superiores de Itacoatiara', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (10, 'Centro de Estudos Superiores de Lábrea', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (11, 'Centro de Estudos Superiores de São Gabriel da Cachoeira', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (12, 'Nucleo de Ensino Superior de Manacapuru', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (13, 'Nucleo de Ensino Superior de Presidente Figueiredo', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (14, 'Nucleo de Ensino Superior de Coari', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (15, 'Nucleo de Ensino Superior de Maues', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (16, 'Nucleo de Ensino Superior de Novo Aripuanã', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (17, 'Nucleo de Ensino Superior de Caruari', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (18, 'Nucleo de Ensino Superior de Manicoré', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (19, 'Nucleo de Ensino Superior de Humaitá', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (20, 'Nucleo de Ensino Superior de Boca do Acre', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (21, 'Nucleo de Ensino Superior de Eirunepé', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (22, 'Nucleo de Ensino Superior de Careiro Castanho', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (23, 'Nucleo de Ensino Superior de Nova Olinda do Norte', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (24, 'Unidade de São Paulo de Olivença', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (25, 'Unidade de Anori', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (26, 'Unidade de Iranduba', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (27, 'Unidade de Borba', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (28, 'Unidade de Fonte Boa', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (29, 'Unidade de São Sebastião do Uatumã', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (30, 'Unidade de Beruri', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (31, 'Unidade de Tapauá', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (32, 'Unidade de Autazes', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (33, 'Unidade de Apuí', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (34, 'Unidade de Tonantins', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (35, 'Unidade de Jutaí', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (36, 'Unidade de Japurá', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (37, 'Unidade de Itapiranga', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (38, 'Unidade de Barcelos', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (39, 'Unidade de Maraã', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (40, 'Unidade de Juruá', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (41, 'Unidade de Nhamundá', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (42, 'Unidade de Novo Airão', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (43, 'Unidade de Boa Vista do Ramos', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (44, 'Unidade de Barreirinha', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (45, 'Unidade de Santo Antonio do Iça', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (46, 'Unidade de Uarini', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (47, 'Unidade de Nova Olinda do Norte', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (48, 'Unidade de Envira', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (49, 'Unidade de Ipixuna', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (50, 'Unidade de Alvarães', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (51, 'Unidade de Codajás', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (52, 'Unidade de Benjamin Constant', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (53, 'Centro de Estudos Superiores do Tropico Humido', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (54, 'Unidade de Urucará', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (55, 'Unidade de Itamarati', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (56, 'Unidade de Manaquiri', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (57, 'Unidade de Atalaia do Norte', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (58, 'Unidade de Anamã', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (59, 'Unidade de Canutama', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (60, 'Unidade de Caapiranga', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (61, 'Unidade de Guajará', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (62, 'Unidade de Pauini', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (63, 'Unidade de Santa Isabel do Rio Negro', 'CESP', 1);
INSERT INTO public.uea_unidade (unidade_id, unidade_nome, unidade_sigla, unidade_status) VALUES (64, 'Unidade de Amaturá', 'CESP', 1);

